"""Emit the cross-language parity fixture for the fingerspelling head.

Two independent implementations have to agree or the model predicts noise without failing: the
trainer builds the frame vector and runs the GRU in PyTorch, and `CtcAlphabetClassifier` does
both again in TypeScript from a flat blob. A mismatch does not throw — it returns confident
nonsense, which is exactly the failure `normalizeHand`'s docstring warns about and which this
repository has already shipped twice.

So this deliberately goes the long way round: it rebuilds the model **from the exported blob**
rather than from the training checkpoint. That way the fixture proves the tensor order in
`lse-alphabet.bin` as well as the arithmetic on top of it.

Synthetic hands rather than corpus frames, reusing `make_parity.build_hand`, so the fixture is
small, readable, committable, and carries nothing from a corpus that must not be redistributed.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import torch

from features import normalize_hand
from lsefs_train import HAND_FLOATS, Speller
from make_parity import build_hand

MODELS = Path(__file__).parent.parent.parent / "public" / "models"
FIXTURE = Path(__file__).parent.parent.parent / "src" / "test" / "fixtures"

#: Enough frames for the hidden state to matter — a single frame would pass even if the engine
#: threw the state away, which is the bug most worth catching here.
FRAMES = 6
#: A different handshape each frame, so the sequence is not a held pose the GRU could ignore.
CURLS = [
    [0.9, 0.0, 0.9, 0.9, 0.9],
    [0.0, 0.0, 0.9, 0.9, 0.9],
    [0.8, 0.05, 0.05, 0.05, 0.05],
    [0.7, 0.9, 0.9, 0.9, 0.05],
    [0.4, 0.45, 0.45, 0.45, 0.45],
    [0.15, 0.9, 0.9, 0.9, 0.9],
]


def main() -> None:
    manifest = json.loads((MODELS / "lse-alphabet.json").read_text())
    blob = np.fromfile(MODELS / "lse-alphabet.bin", dtype=np.float32)

    model = Speller(hidden=manifest["hidden"], layers=manifest["layers"])
    state = model.state_dict()
    offset = 0
    for name in manifest["order"]:
        size = int(np.prod(manifest["shapes"][name]))
        state[name] = torch.tensor(blob[offset : offset + size]).reshape(state[name].shape)
        offset += size
    if offset != blob.size:
        raise SystemExit(f"el blob tiene {blob.size} floats y el manifest describe {offset}")
    model.load_state_dict(state)
    model.eval()

    frames = []
    rows = []
    for step, curls in enumerate(CURLS[:FRAMES]):
        points = build_hand(curls, (step * 0.01, 0.0))
        frames.append({"curls": curls, "offset": [step * 0.01, 0.0]})
        rows.append(normalize_hand(points, "right").reshape(-1).astype(np.float32))

    with torch.no_grad():
        logits = model(torch.tensor(np.stack(rows)).unsqueeze(0))[0]
        probabilities = logits.softmax(-1).numpy()

    FIXTURE.mkdir(parents=True, exist_ok=True)
    (FIXTURE / "alphabet-parity.json").write_text(
        json.dumps(
            {
                "note": "Generated by tools/train/make_alphabet_parity.py. Do not hand-edit.",
                "inputs": HAND_FLOATS,
                "letters": manifest["letters"],
                "frames": frames,
                "posteriors": [[round(float(p), 7) for p in row] for row in probabilities],
            },
            indent=1,
        )
        + "\n"
    )
    print(f"   {FRAMES} frames x {probabilities.shape[1]} clases -> alphabet-parity.json")
    top = probabilities.argmax(-1)
    print(f"   clase ganadora por frame: {top.tolist()}  (0 = blank)")


if __name__ == "__main__":
    main()
